services:
  qr-scanner:
    build: .
    container_name: qr-scanner
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      # Volumen para logs (persistentes)
      - ./logs:/app/logs
    environment:
      - PORT=5000